---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: hello_hapi
  - name: dependency-cache
  #- name: hello_hapi_with_dependencies

run:
  path: hello_hapi/ci/scripts/run_tests.sh
